apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: restapi-monitor
  namespace: jason-space
  labels:
    app: restapi
    prometheus: devops
spec:
  endpoints:
  - port: http
    interval: 15s
    path: /metrics 
  namespaceSelector:
    matchNames:
    - jason-space
  selector:
    matchLabels:
      app: restapi

