apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restapi-pvc
  namespace: jason-space
  labels:
    app: restapi-postgres


spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 20Mi
